#!/bin/sh
unset IFS
set -eu

su root -c "pkgin update && pkgin -y install mozilla-rootcerts wget clang" &&
    su root -c 'mozilla-rootcerts install' &&
    wget https://static.rust-lang.org/rustup/dist/x86_64-unknown-netbsd/rustup-init &&
    chmod +x rustup-init &&
    su vagrant -c './rustup-init -y' &&
    su root -c "sed -i -e 's/^vagrant:.*\$/vagrant: :path=\/home\/vagrant\/.cargo\/bin \/usr\/bin \/bin \/usr\/sbin \/sbin \/usr\/X11R7\/bin \/usr\/X11R6\/bin \/usr\/pkg\/bin \/usr\/pkg\/sbin \/usr\/local\/bin:/' /etc/login.conf" &&
    su root -c 'cap_mkdb /etc/login.conf' &&
    su root -c 'pkgin -y remove mozilla-rootcerts wget' &&
    rm rustup-init
